DropBoxApplication/Controllers/CategoryMasterController.cs
using DropBoxApplication.App_Start;
using DropBoxApplication.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace DropBoxApplication.Controllers
{
    public class CategoryMasterController : BaseController
    {
        // GET: CategoryMaster
        public async Task<ActionResult> Index()
        {
            ViewBag.LoginID = Session["LoginID"].ToString();
            ViewBag.Username = Session["Username"].ToString();
            ViewBag.StoreId = Session["StoreId"].ToString();
            ViewBag.StoreStatus = Session["StoreStatus"].ToString();
            ViewBag.Message = "Your application Daily Activity page.";
            //return View();
            string preurl = GetUrl(2);
            preurl = preurl + "Store/GetAllStoreList";
            StoreMasterModelRootObject pobj = new StoreMasterModelRootObject();
            //List<ProductMasterModel> Prlist = new List<ProductMasterModel>();
            using (HttpClient prclient = new HttpClient())
            {
                HttpResponseMessage responseMessage = await prclient.GetAsync(preurl);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = responseMessage.Content.ReadAsStringAsync().Result;
                    pobj = JsonConvert.DeserializeObject<StoreMasterModelRootObject>(result);
                    IList<SelectListItem> ProSelectList = new List<SelectListItem>();
                    foreach (var item in pobj.data)
                    {
                        ProSelectList.Add(new SelectListItem { Text = item.StoreName, Value = item.StoreId.ToString() });
                    }
                    ProSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Store" });
                    //ProSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
                    ViewBag.StoreList = ProSelectList;
                }
            }

            string murl = GetUrl(2);
            murl = murl + "MenuMaster/GetAllMenuList?StoreId=" + ViewBag.StoreId + "";
            MenuMasterModelRootObject mobj = new MenuMasterModelRootObject();
            //List<MenuMasterModel> mlist = new List<MenuMasterModel>();
            using (HttpClient cclient = new HttpClient())
            {
                HttpResponseMessage responseMessage = await cclient.GetAsync(murl);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = responseMessage.Content.ReadAsStringAsync().Result;
                    mobj = JsonConvert.DeserializeObject<MenuMasterModelRootObject>(result);
                    IList<SelectListItem> mSelectList = new List<SelectListItem>();
                    foreach (var item in mobj.data)
                    {
                        mSelectList.Add(new SelectListItem { Text = item.MenuName, Value = item.MenuId.ToString() });
                    }
                    mSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Menu" });
                    // mSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
                    ViewBag.MenuList = mSelectList;
                }
            }
            CategoryMasterModel category = (CategoryMasterModel)TempData["item"];
            return View(category);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewCategory(FormCollection fc, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                ViewBag.StoreId = Session["StoreId"].ToString();
                int categoryid = 0;
                string storeid = "";
                CategoryMasterModel model = new CategoryMasterModel();
                string CategoryId = fc["CategoryId"];
                string categoryname = fc["CategoryName"];
                string menuid = fc["MenuName"];
                if (ViewBag.StoreId == "0")
                {
                    storeid = fc["StoreName"];
                }
                else
                {
                    storeid = ViewBag.StoreId;
                }
                
                string description = fc["CategoryDescription"];
                string url = GetUrl(2);
                url = url + "Category/AddNewCategory?CategoryId=" + CategoryId + "&CategoryName=" + categoryname + "&menuid=" + menuid + "&storeid=" + storeid + "&CategoryDescription=" + description + "";

                using (HttpClient client = new HttpClient())
                {
                    HttpResponseMessage responseMessage = await client.GetAsync(url);
                    CategoryMasterModelSingleRootObject result = new CategoryMasterModelSingleRootObject();
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        var response = responseMessage.Content.ReadAsStringAsync().Result;
                        var settings = new JsonSerializerSettings
                        {
                            NullValueHandling = NullValueHandling.Ignore,
                            MissingMemberHandling = MissingMemberHandling.Ignore
                        };
                        result = JsonConvert.DeserializeObject<CategoryMasterModelSingleRootObject>(response);
                        if (result.data.CategoryId == 0)
                        {
                            categoryid = Convert.ToInt32(CategoryId);
                        }
                        else
                        {
                            categoryid = result.data.CategoryId;
                        }
                        
                        if (categoryid > 0)
                        {
                            try
                            {
                                var allowedExtensions = new[]
                                {
                                 ".Jpg", ".png", ".jpg", "jpeg",".JPG",
                            };
                                //string imagepath = "http://103.233.79.234/Data/EverGreen_Android/CategoryPictures/";
                                model.CategoryPictures = file.ToString(); //getting complete url                         
                                var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                                var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                                if (allowedExtensions.Contains(ext)) //check what type of extension  
                                {
                                    string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                                    string myfile = + categoryid + ext; //appending the name with id  
                                                                       // store the file inside ~/project folder(Img)  
                                                                       //var path = Path.Combine(imagepath, myfile);
                                    string path = @"C:\inetpub\wwwroot\Data\EverGreen_Android\CategoryPictures\" + Server.HtmlEncode(myfile);
                                    model.CategoryPictures = path;
                                    //file.SaveAs(path);

                                    var fInfo = new FileInfo(myfile);
                                    if (!fInfo.Exists)
                                    {
                                        file.SaveAs(path);
                                    }
                                    else
                                    {
                                        System.IO.File.Copy(path, path, true);
                                    }

                                }
                            }
                            catch (Exception ex)
                            {

                            }
                        }
                        else
                        {
                            ViewBag.message = "Please choose only Image file";
                        }
                    }
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> FindMenuListByStore(string StoreId)
        {

            string strurl = GetUrl(2);
            strurl = strurl + "MenuMaster/GetAllCategoryByStoreIdForWeb?StoreId=" + StoreId;
            CategoryMasterModelRootObject mobj = new CategoryMasterModelRootObject();
            IList<SelectListItem> mSelectList = new List<SelectListItem>();
            using (HttpClient cclient = new HttpClient())
            {
                HttpResponseMessage responseMessage = await cclient.GetAsync(strurl);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = responseMessage.Content.ReadAsStringAsync().Result;
                    mobj = JsonConvert.DeserializeObject<CategoryMasterModelRootObject>(result);
                    foreach (var item in mobj.data)
                    {
                        mSelectList.Add(new SelectListItem { Text = item.MenuName, Value = item.MenuId.ToString() });
                    }
                    //mSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Menu Name" });
                    //mSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
                    ViewBag.MenuList = mSelectList;
                }
            }
            return new JsonResult { Data = mSelectList, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            //return View(new CategoryMasterModel());
        }

        [HttpGet]

DropBoxApplication/Views/CategoryMaster/Index.cshtml
@model DropBoxApplication.Models.CategoryMasterModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("AddNewCategory", "CategoryMaster", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{
    <div class="panel panel-default">
        <div class="panel-heading">Category Master</div>
        <div class="panel-body">
            <div class="col-sm-12 ">
                @Html.HiddenFor(model => model.CategoryId, new { id = "CategoryId" })
                @{var StoreId = Session["StoreId"] != null ? Convert.ToInt32(Session["StoreId"]) : 0;}
                @if (StoreId == 0)
                {
                    <div class="row">
                        <div class="col-lg-3">
                            @Html.DropDownListFor(model => model.StoreName, (IEnumerable<SelectListItem>)ViewBag.StoreList, new { id = "StoreName", @class = "form-group form-control" })
                            @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.DropDownList("MenuName", (IEnumerable<SelectListItem>)ViewBag.MenuList, new { id = "MenuName", @class = "form-group form-control" })
                            @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.CategoryName, new { id = "CategoryName", @class = "form-group form-control", placeholder = "Category Name" })
                            @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.CategoryDescription, new { id = "CategoryDescription", @class = "form-group form-control", placeholder = "Description" })
                            @Html.ValidationMessageFor(model => model.CategoryDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group form-control btn btn-default image-preview-input">
                                <input type="file" id="file" name="file" />
                            </div>
                        </div>
                        <div class="col-lg-7">
                        </div>
                        <div class="col-lg-1">
                            <input type="submit" value="Add" class="form-group form-control btn btn-default" />
                        </div>
                        <div class="col-lg-1">
                            <input type="reset" value="Reset" class="form-group form-control btn btn-default" />
                        </div>
                    </div>
                }
                else
                {
                    <div class="row">
                        @*<div class="col-lg-3">
                                @Html.DropDownListFor(model => model.StoreName, (IEnumerable<SelectListItem>)ViewBag.StoreList, new { id = "StoreName", @class = "form-group form-control" })
                                @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
                            </div>*@
                        <div class="col-lg-3">
                            @Html.DropDownList("MenuName", (IEnumerable<SelectListItem>)ViewBag.MenuList, new { id = "MenuName", @class = "form-group form-control" })
                            @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.CategoryName, new { id = "CategoryName", @class = "form-group form-control", placeholder = "Category Name" })
                            @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.CategoryDescription, new { id = "CategoryDescription", @class = "form-group form-control", placeholder = "Description" })
                            @Html.ValidationMessageFor(model => model.CategoryDescription, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group form-control btn btn-default image-preview-input">
                                <input type="file" id="file" name="file" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-10">
                        </div>
                        <div class="col-lg-1">
                            <input type="submit" value="Add" class="form-group form-control btn btn-default" onclick="refreshdata()" />
                        </div>
                        <div class="col-lg-1">
                            <input type="reset" value="Reset" class="form-group form-control btn btn-default" />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Categories Records</div>
        <div class="panel-body">
            <div class="col-sm-12 ">
                <div id="partial-load"></div>
            </div>
        </div>
    </div>
                    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function refreshdata() {
            $.ajax({
                type: 'GET',
                url: '/CategoryMaster/GetAllCategoryList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-load').empty().append(Results);
                        //statesProgress.hide();
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-load').empty().append(Results.responseText);
                            //statesProgress.hide();
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        }
        $(document).ready(function () {
            //$('#MenuName').change(function () {
            //    debugger
            //    var strMenuName = $('#MenuName option:selected').val();
            //    var qry = {
            //        MenuName: strMenuName,
            //    };
            //var $ddFeName = $('#FieldExective');
            //$ddFeName.empty(); // Clear all Items
            //$ddFeName.append($("<option></option>").val('').html('Please Wait...'));
            $.ajax({
                type: 'GET',
                url: '/CategoryMaster/GetAllCategoryList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-load').empty().append(Results);
                        //statesProgress.hide();
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-load').empty().append(Results.responseText);
                            //statesProgress.hide();
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        });
        //});
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#StoreName').change(function () {
                var strStoreId = 0;
                @{var StoreId = Session["StoreId"] != null ? Convert.ToInt32(Session["StoreId"]) : 0;}
                strStoreId = @StoreId;
                if(strStoreId == 0 ){
                    strStoreId = $('#StoreName option:selected').val();
                    var qry = {
                        StoreId: strStoreId,
                    };
                }
                else{
                    var qry = {
                        StoreId: strStoreId,
                    };
                }
                var $ddMenuName = $('#MenuName');
                $ddMenuName.empty(); // Clear all Items
                $ddMenuName.append($("<option></option>").val('').html('Please Wait...'));
                $.ajax({
                    url: '@Url.Action("FindMenuListByStore", "CategoryMaster")',
                    type: 'GET',
                    dataType: 'json',
                    data: qry,
                    traditional: true,
                    async: true,
                    success: function (d) {
                        $ddMenuName.empty(); // Clear all Items
                        $ddMenuName.append($("<option></option>").val('').html('Select Menu Name'));
                        //$ddMenuName.append($("<option></option>").val('0').html('All'));
                        //$ddMenuName.append($("<option></option>").val(item.MenuId).html(item.MenuName));
                        $.each(d, function (i, item) {
                            //$ddMenuName.append($("<option></option>").val(item).html(item));
                            $ddMenuName.append($('<option value=' + item.Value + '>' + item.Text + '</option>'));
                        });
                        //$.each(data, function () {
                        //    $("#MenuName").append($("<option>                     </option>").val(this['ITEMID']).html(this['ITEMDESC']));
                    },
                    error: function (d) {
                        alert('Error!');
                    }
                });
            });
        });
    </script>
    <style type="text/css">
        table#pruebatabla th,
        table#pruebatabla td {
            white-space: nowrap;
            padding: 3px 6px;
            word-wrap: break-word;
            overflow: hidden;
            /*overflow-x: auto;*/
        }
    </style>
}

<script type="text/javascript">
    //$(document).ready(function () {
    //    $('#StoreName').change(function () {
    //            debugger
    //            var strStoreName = $('#StoreName option:selected').val();
    //            var qry = {
    //                StoreName: strStoreName,
    //            };
    //            //var $ddFeName = $('#FieldExective');
    //            //$ddFeName.empty(); // Clear all Items
    //            //$ddFeName.append($("<option></option>").val('').html('Please Wait...'));
    //           $.ajax({
    //            type: 'Post',
    //            url: '/MenuSetupMaster/GetAllMenuList',
    //            dataType: 'json',
    //            data:qry,
    //            traditional: true,
    //            async: true,
    //            success: function (Results) {
    //                if (Results != null) {
    //                    $('#partial-load').empty().append(Results); statesProgress.hide();
    //                }
    //            },
    //            error: function (Results) {
    //                if (Results != null) {
    //                    $(this).button('loading').delay(1000).queue(function () {
    //                        $('#partial-load').empty().append(Results.responseText);
    //                        statesProgress.hide();
    //                        $('#btnExport').show(); $('#filter').show();
    //                        $(this).button('complete');
    //                        $(this).dequeue();
    //                    });

    //                }
    //            }
    //        });
    //        });
    //    });
</script>

DropBoxApplication/Views/CategoryMaster/_Categorylist.cshtml
@model IEnumerable<DropBoxApplication.Models.CategoryMasterModel>

<div class="clearfix"></div>
@*<div id="states-loading-progress" style="display: none;" class="loader alert alert-dismissible ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong> Please wait..  !</strong>
    </div>*@


<div class="table-responsive tables">
    <div class="ContenedorTabla">
        <table id="pruebatabla" class="table table-striped table-bordered">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="10">No Record's found.</td>
                </tr>
            }
            else
            {
                <thead>
                    <tr>
                        <th id='column-header-1'>Image</th>
                        <th id='column-header-2'>Id</th>
                        <th id='column-header-3'>Category Name</th>
                        <th id='column-header-4'>Category Description</th>
                        <th id='column-header-5'>Store Name</th>
                        <th id='column-header-6'>Menu Name</th>
                        <th id='column-header-7'>Edit</th>
                        <th id='column-header-8'>Remove</th>
                    </tr>
                </thead>
                foreach (var item in Model)
                {
                    <tbody class="searchable">
                        <tr>
                            <td><img src="@item.CategoryPictures" width="40" height="35" /></td>
                            <td>@item.CategoryId</td>
                            <td>@item.CategoryName</td>
                            <td>@item.CategoryDescription</td>
                            <td>@item.StoreName</td>
                            <td>@item.MenuName</td>
                            <td><a href="@Url.Action("GetCategoryById", "CategoryMaster",new { @id= @item.CategoryId})" class="btn btn-success btn-sm">Edit</a></td>
                            <td><a href="@Url.Action("RemoveCategory", "CategoryMaster",new { @id= @item.CategoryId})" cl class="btn btn-primary btn-sm">Remove</a></td>
                        </tr>
                    </tbody>
                }
            }
        </table>
    </div>
</div>



@*<style type="text/css">
        table#pruebatabla th,
        table#pruebatabla td {
            white-space: nowrap;
            padding: 3px 6px;
            word-wrap: break-word;
            overflow: hidden;
            /*overflow-x: auto;*/
        }
    </style>*@
@*<script type="text/javascript">
        $(function () {
            var thHeight = $("table#pruebatabla th:first").height();
            $("table#pruebatabla th").resizable({
                handles: "e",
                minHeight: thHeight,
                maxHeight: thHeight,
                minWidth: 140, maxWidth: 100,
                resize: function (event, ui) {
                    var sizerID = "#" + $(event.target).attr("id") + "-sizer";
                    $(sizerID).width(ui.size.width);
                }
            });
        });
    </script>*@