DropBoxApplication/Controllers/ProductMasterController.cs
using DropBoxApplication.App_Start;
using DropBoxApplication.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DropBoxApplication.Controllers
{
    public class ProductMasterController : BaseController
    {
        // GET: ProductMaster
        public async Task<ActionResult> Index()
        {
            ViewBag.LoginID = Session["LoginID"].ToString();
            ViewBag.Username = Session["Username"].ToString();
            ViewBag.StoreId = Session["StoreId"].ToString();            
            ViewBag.Message = "Your application Daily Activity page.";


            //string url = GetUrl(2);
            //url = url + "Localities/GetAllLocalitiesWithOutPagging";
            //LocalityMasterModelRootObject obj = new LocalityMasterModelRootObject();
            //using (HttpClient client = new HttpClient())
            //{
            //    HttpResponseMessage responseMessage = await client.GetAsync(url);
            //    if (responseMessage.IsSuccessStatusCode)
            //    {
            //        var result = responseMessage.Content.ReadAsStringAsync().Result;
            //        obj = JsonConvert.DeserializeObject<LocalityMasterModelRootObject>(result);

            //        IList<SelectListItem> LSelectList = new List<SelectListItem>();
            //        foreach (var item in obj.data)
            //        {
            //            LSelectList.Add(new SelectListItem { Text = item.LocalityName, Value = item.LocalityId.ToString() });
            //        }
            //        LSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Locality" });

            //        //LSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });

            //        ViewBag.LocalityList = LSelectList;
            //    }
            //}

            //string preurl = GetUrl(2);
            //preurl = preurl + "Store/GetAllStoreList";
            //StoreMasterModelRootObject pobj = new StoreMasterModelRootObject();
            ////List<ProductMasterModel> Prlist = new List<ProductMasterModel>();
            //using (HttpClient prclient = new HttpClient())
            //{
            //    HttpResponseMessage responseMessage = await prclient.GetAsync(preurl);
            //    if (responseMessage.IsSuccessStatusCode)
            //    {
            //        var result = responseMessage.Content.ReadAsStringAsync().Result;
            //        pobj = JsonConvert.DeserializeObject<StoreMasterModelRootObject>(result);
            //        IList<SelectListItem> ProSelectList = new List<SelectListItem>();
            //        foreach (var item in pobj.data)
            //        {
            //            ProSelectList.Add(new SelectListItem { Text = item.StoreName, Value = item.StoreId.ToString() });
            //        }
            //        ProSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Store" });
            //        //ProSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
            //        ViewBag.StoreList = ProSelectList;
            //    }
            //}

            //string murl = GetUrl(2);
            //murl = murl + "MenuMaster/GetAllMenuList";
            //MenuMasterModelRootObject mobj = new MenuMasterModelRootObject();
            ////List<MenuMasterModel> mlist = new List<MenuMasterModel>();
            //using (HttpClient cclient = new HttpClient())
            //{
            //    HttpResponseMessage responseMessage = await cclient.GetAsync(murl);
            //    if (responseMessage.IsSuccessStatusCode)
            //    {
            //        var result = responseMessage.Content.ReadAsStringAsync().Result;
            //        mobj = JsonConvert.DeserializeObject<MenuMasterModelRootObject>(result);
            //        IList<SelectListItem> mSelectList = new List<SelectListItem>();
            //        foreach (var item in mobj.data)
            //        {
            //            mSelectList.Add(new SelectListItem { Text = item.MenuName, Value = item.MenuId.ToString() });
            //        }
            //        mSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Menu" });
            //        // mSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
            //        ViewBag.MenuList = mSelectList;
            //    }
            //}

            string Clienturl = GetUrl(2);
            Clienturl = Clienturl + "Category/GetAllCategoryList?StoreId=" + ViewBag.StoreId + "";
            CategoryMasterModelRootObject cobj = new CategoryMasterModelRootObject();
            //List<CategoryMasterModel> clist = new List<CategoryMasterModel>();
            using (HttpClient cclient = new HttpClient())
            {
                HttpResponseMessage responseMessage = await cclient.GetAsync(Clienturl);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = responseMessage.Content.ReadAsStringAsync().Result;
                    cobj = JsonConvert.DeserializeObject<CategoryMasterModelRootObject>(result);
                    IList<SelectListItem> CSelectList = new List<SelectListItem>();
                    foreach (var item in cobj.data)
                    {
                        CSelectList.Add(new SelectListItem { Text = item.CategoryName, Value = item.CategoryId.ToString() });
                    }
                    CSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Category" });
                    // CSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
                    ViewBag.CategoryList = CSelectList;
                }
            }
            //string preurl = GetUrl(2);
            //preurl = preurl + "ProductMaster/GetAllProductList";
            //ProductMasterModelRootObject pobj = new ProductMasterModelRootObject();
            ////List<ProductMasterModel> Prlist = new List<ProductMasterModel>();
            //using (HttpClient prclient = new HttpClient())
            //{
            //    HttpResponseMessage responseMessage = await prclient.GetAsync(preurl);
            //    if (responseMessage.IsSuccessStatusCode)
            //    {
            //        var result = responseMessage.Content.ReadAsStringAsync().Result;
            //        pobj = JsonConvert.DeserializeObject<ProductMasterModelRootObject>(result);
            //        IList<SelectListItem> ProSelectList = new List<SelectListItem>();
            //        foreach (var item in pobj.data)
            //        {
            //            ProSelectList.Add(new SelectListItem { Text = item.ProductName, Value = item.ProductId.ToString() });
            //        }
            //        ProSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Product" });
            //        ProSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
            //        ViewBag.ProductList = ProSelectList;
            //    }
            //}
            ProductMasterModel product = (ProductMasterModel)TempData["item"];
            return View(product);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewProduct(FormCollection fc, HttpPostedFileBase file)
        {
            //if (ModelState.IsValid)
            //{
            int ProductId = 0;
            ProductMasterModel model = new ProductMasterModel();
            string productId = fc["ProductId"];
            string CategoryName = fc["CategoryName"];
            string ProductName = fc["ProductName"];
            string UnitPrice = fc["UnitPrice"];
            string GST = fc["GST"];
            string Discount = fc["Discount"];
            string TaxType = fc["TaxType"];
            bool Lock = Convert.ToBoolean(fc["Lock"].Split(',')[0]); ;
            string UOM = fc["UOM"];
            string ProductDetails = fc["ProductDetails"];
            string DeliveryCharge = fc["DeliveryCharge"];

            //string ProductId = Convert.ToString(model.ProductId);
            //string ProductDetails = model.ProductDetails;
            //string CategoryName = model.CategoryName;
            //string ProductName = model.ProductName;
            //string UnitPrice = Convert.ToString(model.UnitPrice);
            //string GST = Convert.ToString(model.GST);
            //string Discount = Convert.ToString(model.Discount);
            //string TaxType = Convert.ToString(model.TaxType);
            ////bool Lock = Convert.ToBoolean(fc["Lock"].Split(',')[0]); ;
            //bool Lock = model.Lock;
            //string UOM = Convert.ToString(model.UOM);
            ////string ProductDetails = fc["ProductDetails"];
            string url = GetUrl(2);
            url = url + "Product/AddNewProduct?ProductId=" + productId + "&CategoryName=" + CategoryName + "&ProductName=" + ProductName + "&UnitPrice=" + UnitPrice + "&GST=" + GST + "&Discount=" + Discount + "&TaxType=" + TaxType + "&Lock=" + Lock + "&UOM=" + UOM + "&ProductDetails=" + ProductDetails + "&DeliveryCharge=" + DeliveryCharge + "";

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url);
                ProductMasterModelSingleRootObject result = new ProductMasterModelSingleRootObject();
                if (responseMessage.IsSuccessStatusCode)
                {
                    var response = responseMessage.Content.ReadAsStringAsync().Result;
                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };

DropBoxApplication/Views/ProductMaster/Index.cshtml
@model DropBoxApplication.Models.ProductMasterModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("AddNewProduct", "ProductMaster", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-sm-12 ">
                <div class="row">
                    @Html.HiddenFor(model => model.ProductId, new { id = "ProductId" })
                    <div class="col-lg-3">
                        @Html.DropDownListFor(model => model.CategoryName, (IEnumerable<SelectListItem>)ViewBag.CategoryList, new { id = "CategoryName", @class = "form-group form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.ProductName, new { id = "ProductName", @class = "form-group form-control", placeholder = "ProductName" })
                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.UnitPrice, new { id = "UnitPrice", @class = "form-group form-control", placeholder = "UnitPrice" })
                        @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.GST, new { id = "GST", @class = "form-group form-control", placeholder = "GST" })
                        @Html.ValidationMessageFor(model => model.GST, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.Discount, new { id = "Discount", @class = "form-group form-control", placeholder = "Discount" })
                        @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.UOM, new { id = "UOM", @class = "form-group form-control", placeholder = "UOM" })
                        @Html.ValidationMessageFor(model => model.UOM, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.ProductDetails, new { id = "ProductDetails", @class = "form-group form-control", placeholder = "ProductDetails" })
                        @Html.ValidationMessageFor(model => model.ProductDetails, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.DeliveryCharge, new { id = "DeliveryCharge", @class = "form-group form-control", placeholder = "Delivery Charge" })
                        @Html.ValidationMessageFor(model => model.DeliveryCharge, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-1">
                        <label for="TaxType" class="control-label">
                            Including Tax
                        </label>
                    </div>
                    <div class="col-lg-1">
                        @Html.RadioButtonFor(model => model.TaxType, "I", new { id = "TaxType", @class = "form-group form-control" })
                    </div>
                    <div class="col-lg-1">
                        <label for="TaxType" class="control-label">
                            Exclusive Tax
                        </label>
                    </div>
                    <div class="col-lg-1">
                        @Html.RadioButtonFor(model => model.TaxType, "X", new { id = "TaxType", @class = "form-group form-control" })
                    </div>
                    <div class="col-lg-2">
                        <label for="Lock" class="control-label">
                            Product Lock
                        </label>
                        @Html.CheckBoxFor(model => model.Lock, new { InputType = "checkbox", name = "Lock", id = "Lock", @class = "form-group form-control switch" })
                        @Html.ValidationMessageFor(model => model.Lock, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-lg-3">
                        <div class="btn btn-default image-preview-input form-group form-control">
                            <input type="file" id="file" name="file" />
                        </div>
                    </div>
                    <div class="col-lg-1">
                        <input type="submit" value="Add" id="btnAdd" class="form-group form-control btn btn-default" onclick="refreshdata()" />
                    </div>
                    <div class="col-lg-1">
                        <input type="reset" value="Reset" id="btnReset" class="form-group form-control btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1 class="panel-title">
                <a role="button" data-toggle="collapse" href="#partial-load" aria-expanded="true" aria-controls="partial-load">
                    <i class="more-less glyphicon glyphicon-plus"></i>
                    Products In Stock
                </a>
            </h1>
        </div>
        <div class="panel-body">
            <div class="col-sm-12 ">
                <div id="partial-load"></div>
            </div>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1 class="panel-title">
                <a role="button" data-toggle="collapse" href="#partial-loadProduct" aria-expanded="true" aria-controls="partial-loadProduct">
                    <i class="more-less glyphicon glyphicon-plus"></i>
                    Products OutOf Stock
                </a>
            </h1>
        </div>
        <div class="panel-body">
            <div class="col-sm-12 ">
                <div id="partial-loadProduct"></div>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/Content/boostrapSwitch.css" rel="stylesheet" />
    <style>
        .panel-heading {
            padding: 0px 15px;
        }

        .panel-group .panel {
            border-radius: 0;
            box-shadow: none;
            border-color: #EEEEEE;
        }

        .panel-default > .panel-heading {
            padding: 0;
            border-radius: 0;
            color: #212121;
            background-color: #FAFAFA;
            border-color: #EEEEEE;
        }

        .panel-title {
            font-size: 14px;
        }

            .panel-title > a {
                display: block;
                padding: 15px;
                text-decoration: none;
            }

        .more-less {
            float: right;
            color: white;
        }

        .panel-default > .panel-heading + .panel-collapse > .panel-body {
            border-top-color: #EEEEEE;
        }
    </style>
    <script>
        function refreshdata() {
            ProductInStockList();
            ProductOutOfStockList();
        }
        function toggleIcon(e) {
            $(e.target)
                .prev('.panel-heading')
                .find(".more-less")
                .toggleClass('glyphicon-plus glyphicon-minus');
        }
        $('.panel panel-primary').on('hidden.bs.collapse', toggleIcon);
        $('.panel panel-primary').on('shown.bs.collapse', toggleIcon);
    </script>
    <script>
        $(document).ready(function () {
            ProductInStockList();
            ProductOutOfStockList();
        });

        function funCheck(t) {
            if (t.is(':checked')) {
                ProductInStockList();
                ProductOutOfStockList();
            }
            else {
                ProductInStockList();
                ProductOutOfStockList();
            }
        }


        var ProductInStockList = function () {
            $.ajax({
                type: 'GET',
                url: '/ProductMaster/GetAllProductList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-load').empty().append(Results);
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-load').empty().append(Results.responseText);
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        }
        var ProductOutOfStockList = function () {

            $.ajax({
                type: 'GET',
                url: '/ProductMaster/GetAllOutOfStockProductList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-loadProduct').empty().append(Results);
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-loadProduct').empty().append(Results.responseText);
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        }

    </script>



    @*<script>
            function boxDisableOut(t) {
                var id = (t.val());
                var qry = {
                    ProductId: id,
                };

                if (t.is(':checked')) {
                    $.ajax({
                        url: "/ProductMaster/ProductLockOff?strProductId=" + id + "",
                        type: "GET",
                        //data: qry,
                        contentType: "application/json;charset=utf-8",
                        dataType: "JSON",
                        success: function (result) {
                        },
                        error: function (errormessage) {
                            //alert(errormessage.responseText);
                        }
                    });
                }
                else {
                    $.ajax({
                        url: "/ProductMaster/ProductLockOn?strProductId=" + id + "",
                        type: "GET",
                        //data: qry,
                        contentType: "application/json;charset=utf-8",
                        dataType: "JSON",
                        success: function (result) {

                        },
                        error: function (errormessage) {
                            //alert(errormessage.responseText);
                        }
                    });
                }
            };
        </script>*@
    <style type="text/css">
        table#pruebatabla th,
        table#pruebatabla td {
            white-space: nowrap;
            padding: 3px 6px;
            word-wrap: break-word;
            overflow: hidden;
        }
    </style>

}

DropBoxApplication/Views/ProductMaster/_OutOfStockProductList.cshtml
@model IEnumerable<DropBoxApplication.Models.ProductMasterModel>

<div class="clearfix"></div>
<div class="table-responsive tables">
    <div class="ContenedorTabla">
        <table id="pruebatabla" class="table table-striped table-bordered">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="10">No Record's found.</td>
                </tr>
            }
            else
            {
                <thead>
                    <tr>
                        <th id='column-header-1'>Image</th>
                        <th id='column-header-2'>Id</th>
                        <th id='column-header-3'>Product Name</th>
                        <th id='column-header-4'>Category Name</th>
                        <th id='column-header-5'>Unit Price</th>
                        <th id='column-header-6'>GST</th>
                        <th id='column-header-7'>Discount</th>
                        <th id='column-header-8'>UOM</th>
                        <th id='column-header-9'>ProductDetails</th>
                        <td id='column-header-10'>Lock</td>
                        <th id='column-header-11'>Edit</th>
                        <th id='column-header-12'>Remove</th>
                    </tr>
                </thead>
                foreach (var item in Model)
                {
                    <tbody class="searchable">
                        <tr>
                            <td><img src="@item.ProductPicturesUrl" width="40" height="35" /></td>
                            <td>@item.ProductId</td>
                            <td>@item.ProductName</td>
                            <td>@item.CategoryName</td>
                            <td>@item.UnitPrice</td>
                            <td>@item.GST</td>
                            <td>@item.Discount</td>
                            <td>@item.UOM</td>
                            @*<td>@item.HSN</td>
                                <td>@item.SweetsReset</td>*@
                            <td>@item.ProductDetails</td>
                            <td>
                                @if (item.Lock)
                                {
                                    <label class="switch">
                                        <input type="checkbox" name="ProductStatus"  id="ProductStatus" value="@item.ProductId" onclick="boxDisable($(this)); funCheck($(this));">
                                        <span class="slider round"></span>
                                    </label>
                                }
                                else
                                {
                                    <label class="switch">
                                        <input type="checkbox" name="ProductStatus" checked id="ProductStatus" value="@item.ProductId" onclick="boxDisable($(this)); funCheck($(this));">
                                        <span class="slider round"></span>
                                    </label>
                                }
                            </td>
                            @*<td>@item.Lock</td>*@
                            <td><a href="@Url.Action("GetProductById", "ProductMaster",new { @id= @item.ProductId})" class="btn btn-success btn-sm">Edit</a></td>
                            <td><a href="@Url.Action("RemoveProduct", "ProductMaster",new { @id= @item.ProductId})" class="btn btn-primary btn-sm">Remove</a></td>
                        </tr>
                    </tbody>
                }
            }
        </table>
    </div>
</div>
<script>
    function boxDisable(t) {
        var id = (t.val());
        var qry = {
            ProductId: id,
        };

        if (t.is(':checked')) {
            $.ajax({
                url: "/ProductMaster/ProductLockOff?strProductId=" + id + "",
                type: "GET",
                //data: qry,
                contentType: "application/json;charset=utf-8",
                dataType: "JSON",
                success: function (result) {

                },
                error: function (errormessage) {
                    //alert(errormessage.responseText);
                }
            });
        }
        else {
            $.ajax({
                url: "/ProductMaster/ProductLockOn?strProductId=" + id + "",
                type: "GET",
                //data: qry,
                contentType: "application/json;charset=utf-8",
                dataType: "JSON",
                success: function (result) {

                },
                error: function (errormessage) {
                    //alert(errormessage.responseText);
                }
            });
        }
    };
</script>