DropBoxApplication/Controllers/MenuMasterController.cs
using DropBoxApplication.App_Start;
using DropBoxApplication.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DropBoxApplication.Controllers
{
    public class MenuMasterController : BaseController
    {
        // GET: MenuMaster
        public async Task<ActionResult> Index()
        {
            ViewBag.LoginID = Session["LoginID"].ToString();
            ViewBag.Username = Session["Username"].ToString();
            ViewBag.StoreStatus = Session["StoreStatus"].ToString();
            ViewBag.Message = "Your application Daily Activity page.";
            //return View();
            string preurl = GetUrl(2);
            preurl = preurl + "Store/GetAllStoreList";
            StoreMasterModelRootObject pobj = new StoreMasterModelRootObject();
            //List<ProductMasterModel> Prlist = new List<ProductMasterModel>();
            using (HttpClient prclient = new HttpClient())
            {
                HttpResponseMessage responseMessage = await prclient.GetAsync(preurl);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var result = responseMessage.Content.ReadAsStringAsync().Result;
                    pobj = JsonConvert.DeserializeObject<StoreMasterModelRootObject>(result);
                    IList<SelectListItem> ProSelectList = new List<SelectListItem>();
                    foreach (var item in pobj.data)
                    {
                        ProSelectList.Add(new SelectListItem { Text = item.StoreName, Value = item.StoreId.ToString() });
                    }
                    ProSelectList.Insert(0, new SelectListItem() { Value = "", Text = "Select Store" });
                    //ProSelectList.Insert(1, new SelectListItem() { Value = "0", Text = "All" });
                    ViewBag.StoreList = ProSelectList;
                }
            }
            MenuMasterModel menu = (MenuMasterModel)TempData["item"];
            return View(menu);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewMenu(FormCollection fc, HttpPostedFileBase file)
        {
            ViewBag.StoreId = Session["StoreId"].ToString();
            if (ModelState.IsValid)
            {
                int MenuId = 0;
                string storeid = "";
                MenuMasterModel model = new MenuMasterModel();
                string menuid = fc["MenuId"];
                string menuname = fc["MenuName"];
                string menuprice = fc["MenuPrice"];
                if (ViewBag.StoreId == "0")
                {
                    storeid = fc["StoreName"];
                }
                else
                {
                    storeid = ViewBag.StoreId;
                }

                string url = GetUrl(2);
                url = url + "MenuMaster/AddNewMenu?menuid=" + menuid + "&menuname=" + menuname + "&menuprice=" + menuprice + "&storeid=" + storeid + "";

                using (HttpClient client = new HttpClient())
                {
                    HttpResponseMessage responseMessage = await client.GetAsync(url);
                    MenuMasterModelSignleRootObject result = new MenuMasterModelSignleRootObject();
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        var response = responseMessage.Content.ReadAsStringAsync().Result;
                        var settings = new JsonSerializerSettings
                        {
                            NullValueHandling = NullValueHandling.Ignore,
                            MissingMemberHandling = MissingMemberHandling.Ignore
                        };
                        result = JsonConvert.DeserializeObject<MenuMasterModelSignleRootObject>(response);
                        if (result.data.MenuId == 0)
                        {
                            MenuId = Convert.ToInt32(menuid);
                        }
                        else
                        {
                            MenuId = result.data.MenuId;
                        }
                        if (MenuId > 0)
                        {
                            try
                            {
                                var allowedExtensions = new[]
                                {
                                 ".Jpg", ".png", ".jpg", "jpeg",".JPG",
                            };
                                //string imagepath = "http://103.233.79.234/Data/EverGreen_Android/LocalityPictures/";
                                model.ImageUrl = file.ToString(); //getting complete url                         
                                var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                                var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                                if (allowedExtensions.Contains(ext)) //check what type of extension  
                                {
                                    string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                                    string myfile = +MenuId + ext; //appending the name with id  
                                                                   // store the file inside ~/project folder(Img)  
                                                                   //var path = Path.Combine(imagepath, myfile);
                                    string path = @"C:\inetpub\wwwroot\Data\EverGreen_Android\\MenuPictures\" + Server.HtmlEncode(myfile);
                                    model.ImageUrl = path;
                                    //file.SaveAs(path);
                                    var fInfo = new FileInfo(myfile);
                                    if (!fInfo.Exists)
                                    {
                                        file.SaveAs(path);
                                    }
                                    else
                                    {
                                        System.IO.File.Copy(path, path, true);
                                    }
                                }
                            }
                            catch (Exception ex)
                            {

                            }

                        }
                        else
                        {
                            ViewBag.message = "Please choose only Image file";
                        }
                    }
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetAllMenuList()
        {
            List<MenuMasterModel> olist = new List<MenuMasterModel>();
            ViewBag.StoreId = Session["StoreId"].ToString();
            string url = GetUrl(2);
            url = url + "MenuMaster/GetAllMenuList?StoreId=" + ViewBag.StoreId + "";

            using (HttpClient client = new HttpClient())
            {

                HttpResponseMessage responseMessage = await client.GetAsync(url);
                MenuMasterModelRootObject result = new MenuMasterModelRootObject();
                if (responseMessage.IsSuccessStatusCode)
                {
                    var response = responseMessage.Content.ReadAsStringAsync().Result;
                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
                    result = JsonConvert.DeserializeObject<MenuMasterModelRootObject>(response);
                    olist = result.data;
                    ViewBag.LocalityList = olist;
                }
            }
            return PartialView("_Menulist", olist);
        }

        [HttpGet]
        public async Task<ActionResult> RemoveMenu(int id)
        {
            //string strint = id.Trim().ToString();
            //var intid = Convert.ToInt32(strint);
            List<MenuMasterModel> olist = new List<MenuMasterModel>();

            MenuMasterModelRootObject obj = new MenuMasterModelRootObject();

            string url = GetUrl(2);
            url = url + "MenuMaster/RemoveMenu?id=" + Convert.ToInt32(id) + "";
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var response = responseMessage.Content.ReadAsStringAsync().Result;
                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
                    obj = JsonConvert.DeserializeObject<MenuMasterModelRootObject>(response, settings);
                    olist = obj.data;
                    ViewBag.TransactionList = olist;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> GetMenuById(int id)
        {
            //string strint = id.Trim().ToString();
            //var intid = Convert.ToInt32(strint);
            MenuMasterModel pro = new MenuMasterModel();

            MenuMasterModelSignleRootObject obj = new MenuMasterModelSignleRootObject();

            string url = GetUrl(2);
            url = url + "MenuMaster/GetMenuById?id=" + Convert.ToInt32(id) + "";
            using (HttpClient client = new HttpClient())
            {

DropBoxApplication/Views/MenuMaster/Index.cshtml
@model DropBoxApplication.Models.MenuMasterModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("AddNewMenu", "MenuMaster", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
{
    <div class="panel panel-default">
        <div class="panel-heading">Menu Master</div>
        <div class="panel-body">
            <div class="col-sm-12 ">

                @Html.HiddenFor(model => model.MenuId, new { id = "MenuId" })
                @{var StoreId = Session["StoreId"] != null ? Convert.ToInt32(Session["StoreId"]) : 0;}
                @{var StoreStatus = Convert.ToBoolean(Session["StoreStatus"]);}
                @if (StoreId == 0)
                {<div class="row">
                    <div class="col-lg-3">
                        @Html.DropDownListFor(model => model.StoreName, (IEnumerable<SelectListItem>)ViewBag.StoreList, new { id = "StoreName1", @class = "form-group form-control" })
                        @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.MenuName, new { id = "MenuName", @class = "form-group form-control", placeholder = "Menu Name" })
                        @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        @Html.TextBoxFor(model => model.MenuPrice, new { id = "MenuPrice", @class = "form-group form-control", placeholder = "Menu Price" })
                        @Html.ValidationMessageFor(model => model.MenuPrice, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group form-control btn btn-default image-preview-input">
                            <input type="file" id="file" name="file" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-10">
                    </div>
                    <div class="col-lg-1">
                        <input type="submit" value="Add" class="form-group form-control btn btn-default" />
                    </div>
                    <div class="col-lg-1">
                        <input type="reset" value="Reset" class="form-group form-control btn btn-default" />
                    </div>
                </div>
                }
                else
                {
                    <div class="row">
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.MenuName, new { id = "MenuName", @class = "form-group form-control", placeholder = "Menu Name" })
                            @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            @Html.TextBoxFor(model => model.MenuPrice, new { id = "MenuPrice", @class = "form-group form-control", placeholder = "Menu Price" })
                            @Html.ValidationMessageFor(model => model.MenuPrice, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group form-control btn btn-default image-preview-input">
                                <input type="file" id="file" name="file" />
                            </div>
                        </div>
                        <div class="col-lg-1">

                        </div>
                        <div class="col-lg-1">
                            <input type="submit" value="Add" class="form-group form-control btn btn-default" onclick="refreshdata()" />
                        </div>
                        <div class="col-lg-1">
                            <input type="reset" value="Reset" class="form-group form-control btn btn-default" />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Menu Records</div>
        <div class="panel-body">
            <div class="col-sm-12 ">
                <div id="partial-load"></div>
            </div>
        </div>
    </div>
                    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <style type="text/css">
        table#pruebatabla th,
        table#pruebatabla td {
            white-space: nowrap;
            padding: 3px 6px;
            word-wrap: break-word;
            overflow: hidden;
            /*overflow-x: auto;*/
        }
    </style>
    <script>
        function refreshdata() {           
            $.ajax({
                type: 'GET',
                url: '/MenuMaster/GetAllMenuList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-load').empty().append(Results);
                        //statesProgress.hide();
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-load').empty().append(Results.responseText);
                            //statesProgress.hide();
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        }
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                url: '/MenuMaster/GetAllMenuList',
                dataType: 'json',
                //data: qry,
                traditional: true,
                async: true,
                success: function (Results) {
                    if (Results != null) {
                        $('#partial-load').empty().append(Results);
                        //statesProgress.hide();
                    }
                },
                error: function (Results) {
                    if (Results != null) {
                        $(this).button('loading').delay(1000).queue(function () {
                            $('#partial-load').empty().append(Results.responseText);
                            //statesProgress.hide();
                            $('#btnExport').show(); $('#filter').show();
                            $(this).button('complete');
                            $(this).dequeue();
                        });

                    }
                }
            });
        });
    </script>
}

DropBoxApplication/Views/MenuMaster/_Menulist.cshtml
@model IEnumerable<DropBoxApplication.Models.MenuMasterModel>

<div class="clearfix"></div>
@*<div id="states-loading-progress" style="display: none;" class="loader alert alert-dismissible ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong> Please wait..  !</strong>
    </div>*@


<div class="table-responsive tables">
    <div class="ContenedorTabla">
        <table id="pruebatabla" class="table table-striped table-bordered">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="10">No Record's found.</td>
                </tr>
            }
            else
            {
                <thead>
                    <tr>
                        <th id='column-header-1'>Image</th>
                        <th id='column-header-2'>Id</th>
                        <th id='column-header-3'>Menu Name</th>
                        <th id='column-header-4'>Menu Price</th>
                        <th id='column-header-5'>Store Name</th>
                        <th id='column-header-6'>Edit</th>
                        <th id='column-header-7'>Remove</th>
                    </tr>
                </thead>
                foreach (var item in Model)
                {
                    <tbody class="searchable">
                        <tr>
                            <td><img src="@item.ImageUrl" width="40" height="35" /></td>
                            <td>@item.MenuId</td>
                            <td>@item.MenuName</td>
                            <td>@item.MenuPrice</td>
                            <td>@item.StoreName</td>
                            <td><a href="@Url.Action("GetMenuById", "MenuMaster",new { @id= @item.MenuId})" class="btn btn-success btn-sm">Edit</a></td>
                            <td><a href="@Url.Action("RemoveMenu", "MenuMaster",new { @id= @item.MenuId})" class="btn btn-primary btn-sm">Remove</a></td>
                        </tr>
                    </tbody>
                }
            }
        </table>
    </div>
</div>



@*<style type="text/css">
        table#pruebatabla th,
        table#pruebatabla td {
            white-space: nowrap;
            padding: 3px 6px;
            word-wrap: break-word;
            overflow: hidden;
            /*overflow-x: auto;*/
        }
    </style>*@
@*<script type="text/javascript">
        $(function () {
            var thHeight = $("table#pruebatabla th:first").height();
            $("table#pruebatabla th").resizable({
                handles: "e",
                minHeight: thHeight,
                maxHeight: thHeight,
                minWidth: 140, maxWidth: 100,
                resize: function (event, ui) {
                    var sizerID = "#" + $(event.target).attr("id") + "-sizer";
                    $(sizerID).width(ui.size.width);
                }
            });
        });
    </script>*@